<?php

namespace App\PDFs;

use App\Models\Customer;
use App\Models\CustomerTransaction;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;

/**
 * Generates a customer statement PDF using DomPDF.
 */
class CustomerStatementPDF
{
    /**
     * @param  Collection<int, CustomerTransaction>  $transactions
     */
    public function __construct(
        private readonly Customer $customer,
        private readonly Collection $transactions,
        private readonly int $openingBalance,
        private readonly int $closingBalance,
        private readonly Carbon $from,
        private readonly Carbon $to,
    ) {}

    /**
     * Generate and return PDF content.
     */
    public function generate(): string
    {
        $html = $this->buildHtml();

        $pdf = \Barryvdh\DomPDF\Facade\Pdf::loadHTML($html)
            ->setPaper('a4', 'portrait');

        return $pdf->output();
    }

    /**
     * Generate, store, and return a signed URL.
     */
    public function storeAndGetUrl(): string
    {
        $content = $this->generate();
        $companyId = $this->customer->company_id;
        $filename = "statements/customer-{$this->customer->id}-".now()->timestamp.'.pdf';
        $path = "{$companyId}/{$filename}";

        \Illuminate\Support\Facades\Storage::disk('local')
            ->put("private/{$path}", $content);

        return \Illuminate\Support\Facades\URL::temporarySignedRoute(
            'statements.download',
            now()->addHour(),
            ['path' => $path]
        );
    }

    private function buildHtml(): string
    {
        $company = $this->customer->company;
        $rows = '';
        $runningBalance = $this->openingBalance;

        foreach ($this->transactions as $txn) {
            $runningBalance += $txn->amount;
            $debit = $txn->amount > 0 ? $this->formatMoney($txn->amount) : '';
            $credit = $txn->amount < 0 ? $this->formatMoney(abs($txn->amount)) : '';
            $balance = $this->formatMoney($runningBalance);
            $date = $txn->transaction_date->format('d M Y');
            $rows .= "<tr><td>{$date}</td><td>{$txn->type}</td><td>{$txn->description}</td><td class='r'>{$debit}</td><td class='r'>{$credit}</td><td class='r'>{$balance}</td></tr>";
        }

        $opening = $this->formatMoney($this->openingBalance);
        $closing = $this->formatMoney($this->closingBalance);
        $dateRange = $this->from->format('d M Y').' – '.$this->to->format('d M Y');
        $companyName = e($company->name ?? 'GenERP BD');
        $customerName = e($this->customer->name);
        $customerCode = e($this->customer->customer_code ?? '');
        $generated = now()->format('d M Y H:i');

        return <<<HTML
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body { font-family: sans-serif; font-size: 11px; margin: 20px; }
                h1 { font-size: 18px; margin: 0; }
                h2 { font-size: 14px; color: #555; margin: 5px 0 15px; }
                table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                th, td { border: 1px solid #ccc; padding: 5px 8px; text-align: left; }
                th { background: #f5f5f5; }
                .r { text-align: right; }
                .header { display: flex; justify-content: space-between; margin-bottom: 15px; }
                .summary { margin: 10px 0; padding: 8px; background: #f9f9f9; }
                .footer { margin-top: 20px; font-size: 9px; color: #999; text-align: center; }
            </style>
        </head>
        <body>
            <h1>{$companyName}</h1>
            <h2>Customer Statement</h2>
            <p><strong>Customer:</strong> {$customerName} ({$customerCode})<br>
               <strong>Period:</strong> {$dateRange}</p>
            <div class="summary">
                <strong>Opening Balance:</strong> {$opening}
            </div>
            <table>
                <thead>
                    <tr><th>Date</th><th>Type</th><th>Description</th><th class="r">Debit (৳)</th><th class="r">Credit (৳)</th><th class="r">Balance (৳)</th></tr>
                </thead>
                <tbody>
                    {$rows}
                </tbody>
            </table>
            <div class="summary">
                <strong>Closing Balance:</strong> {$closing}
            </div>
            <div class="footer">
                Generated by GenERP BD on {$generated}
            </div>
        </body>
        </html>
        HTML;
    }

    private function formatMoney(int $paise): string
    {
        return number_format($paise / 100, 2);
    }
}
